import type { MenuData } from "@/types"

export const MENU_DATA: MenuData = {
  appetizers: [
    { name: "Vegetable Samosas", price: 5.95, hasSpice: false },
    { name: "Vegetable Pakoras", price: 7.95, hasSpice: false },
    { name: "Chicken Pakoras", price: 8.95, hasSpice: false },
    { name: "Onion Bhaji", price: 7.95, hasSpice: false },
  ],
  tandoori: [
    { name: "Tandoori Chicken", price: 14.95, hasSpice: true },
    { name: "Chicken Tikka", price: 14.95, hasSpice: true },
    { name: "Tandoori Shrimp", price: 18.95, hasSpice: true },
    { name: "Tandoori Mix Grill Dinner", price: 20.95, hasSpice: true },
    { name: "Paneer Tikka", price: 14.95, hasSpice: true },
    { name: "Sheesh Kebab", price: 15.95, hasSpice: true },
  ],
  vegetableDishes: [
    { name: "Daal Maharani", price: 12.95, hasSpice: true },
    { name: "Chana Masala", price: 12.95, hasSpice: true },
    { name: "Bengan Bhartha", price: 14.95, hasSpice: true },
    { name: "Vegetable Korma", price: 14.95, hasSpice: true },
    { name: "Aloo Gobhi", price: 13.95, hasSpice: true },
    { name: "Aloo Matar", price: 12.95, hasSpice: true },
    { name: "Mushroom Bhajee", price: 14.95, hasSpice: true },
    { name: "Palak Paneer", price: 14.95, hasSpice: true },
    { name: "Matar Paneer", price: 14.95, hasSpice: true },
    { name: "Kadhi Pakora", price: 12.95, hasSpice: true },
    { name: "Karahi Aloo Palak", price: 14.95, hasSpice: true },
    { name: "Malai Kofta", price: 15.95, hasSpice: true },
    { name: "Paneer Tika Masala", price: 15.95, hasSpice: true },
  ],
  chickenDishes: [
    { name: "Chicken Curry", price: 14.95, hasSpice: true },
    { name: "Chicken Vindaloo", price: 14.95, hasSpice: true },
    { name: "Sag Chicken", price: 14.95, hasSpice: true },
    { name: "Chicken Korma", price: 15.95, hasSpice: true },
    { name: "Chicken Do Piaza", price: 14.95, hasSpice: true },
    { name: "Chicken Mushroom", price: 14.95, hasSpice: true },
    { name: "Karahi Chicken", price: 14.95, hasSpice: true },
    { name: "Karahi Tandoor Chicken Sag", price: 14.95, hasSpice: true },
    { name: "Methi Chicken", price: 14.95, hasSpice: true },
    { name: "Achari Chicken", price: 14.95, hasSpice: true },
    { name: "Chicken Tikka Masala", price: 16.95, hasSpice: true },
    { name: "Murg Makhani", price: 16.95, hasSpice: true },
    { name: "Madrasi Chicken", price: 16.95, hasSpice: true },
    { name: "Chicken Biryani", price: 14.95, hasSpice: true },
  ],
  lambDishes: [
    { name: "Lamb Curry (Rogan Josh)", price: 16.95, hasSpice: true },
    { name: "Sag Lamb", price: 16.95, hasSpice: true },
    { name: "Lamb Korma", price: 17.95, hasSpice: true },
    { name: "Lamb Vindaloo", price: 16.95, hasSpice: true },
    { name: "Lamb Dopiaza", price: 16.95, hasSpice: true },
    { name: "Madrasi Lamb", price: 17.95, hasSpice: true },
    { name: "Karahi Lamb", price: 17.95, hasSpice: true },
    { name: "Achari Lamb", price: 16.95, hasSpice: true },
    { name: "Lamb Biryani", price: 17.95, hasSpice: true },
  ],
  goatDishes: [
    { name: "Goat Curry", price: 18.95, hasSpice: true },
    { name: "Achaari Goat", price: 18.95, hasSpice: true },
    { name: "Goat Masala", price: 18.95, hasSpice: true },
    { name: "Goat Kadahi", price: 18.95, hasSpice: true },
    { name: "Goat Biryani", price: 17.95, hasSpice: true },
  ],
  seafoodDishes: [
    { name: "Shrimp Curry", price: 18.95, hasSpice: true },
    { name: "Shrimp Vindaloo", price: 18.95, hasSpice: true },
    { name: "Sag Shrimp", price: 18.95, hasSpice: true },
    { name: "Chili Shrimp", price: 18.95, hasSpice: true },
    { name: "Fish Curry", price: 18.95, hasSpice: true },
    { name: "Fish Vindaloo", price: 18.95, hasSpice: true },
    { name: "Garlic Shrimp", price: 18.95, hasSpice: true },
    { name: "Tandoori Shrimp Masala", price: 20.95, hasSpice: true },
    { name: "Madrasi Shrimp", price: 20.95, hasSpice: true },
    { name: "Shrimp Biryani", price: 18.95, hasSpice: true },
  ],
  riceDishes: [
    { name: "Basmati Rice Plate", price: 2.95, hasSpice: false },
    { name: "Basmati Palao Rice", price: 5.95, hasSpice: false },
    { name: "Vegetable Biryani", price: 12.95, hasSpice: true },
  ],
  tandooriBreads: [
    { name: "Tandoori Roti", price: 2.95, hasSpice: false },
    { name: "Garlic Roti", price: 2.95, hasSpice: false },
    { name: "Naan", price: 2.95, hasSpice: false },
    { name: "Garlic Naan", price: 3.95, hasSpice: false },
    { name: "Poori", price: 4.95, hasSpice: false },
    { name: "Parantha", price: 3.95, hasSpice: false },
    { name: "Aloo Kulcha or Parantha", price: 4.95, hasSpice: false },
    { name: "Gobhi Kulcha or Parantha", price: 4.95, hasSpice: false },
    { name: "Keema Naan or Parantha", price: 4.95, hasSpice: false },
    { name: "Onion Kulcha or Paranthas", price: 4.95, hasSpice: false },
    { name: "Chilli Kulcha or Parantha", price: 4.95, hasSpice: false },
    { name: "Paneer Kulcha", price: 5.95, hasSpice: false },
  ],
  beverages: [
    { name: "Coffee", price: 2.95, hasSpice: false },
    { name: "Indian Tea", price: 3.95, hasSpice: false },
    { name: "Iced Tea", price: 2.95, hasSpice: false },
    { name: "Punjabi Lassi", price: 4.95, hasSpice: false },
    { name: "Mango Lassi", price: 4.95, hasSpice: false },
    { name: "Milk", price: 3.95, hasSpice: false },
    { name: "Soda", price: 3.25, hasSpice: false },
    { name: "Club Soda", price: 3.25, hasSpice: false },
  ],
  desserts: [
    { name: "Kulfi (Indian style ice cream)", price: 4.95, hasSpice: false },
    { name: "Mango Kulfi", price: 4.95, hasSpice: false },
    { name: "Kheer (Rice pudding)", price: 4.95, hasSpice: false },
    { name: "Gulab Jamon", price: 4.95, hasSpice: false },
    { name: "Mango Fruit Pudding", price: 4.95, hasSpice: false },
  ],
  extras: [
    { name: "Raita", price: 3.95, hasSpice: false },
    { name: "Pickle/Chutney", price: 2.95, hasSpice: false },
    { name: "Papadum", price: 2.95, hasSpice: false },
    { name: "Salad", price: 3.95, hasSpice: false },
  ],
}

export const CATEGORY_NAMES: Record<string, string> = {
  appetizers: "Appetizers",
  tandoori: "Tandoori",
  vegetableDishes: "Vegetable Dishes",
  chickenDishes: "Chicken Dishes",
  lambDishes: "Lamb Dishes",
  goatDishes: "Goat Dishes",
  seafoodDishes: "Seafood Dishes",
  riceDishes: "Rice Dishes",
  tandooriBreads: "Tandoori Breads",
  beverages: "Beverages",
  desserts: "Desserts",
  extras: "Extras",
}
